<a href="https://colab.research.google.com/github/fyhao/colab/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
I am fyhao, in this notebook, I am going to learn Tensorflow fundamentals of tensor using Tensorflow by following this udemy course https://www.udemy.com/course/tensorflow-developer-certificate-machine-learning-zero-to-mastery/learn/lecture/24779114#overview
Lets get started.

In [21]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,0,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  0, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7.],
                              [8.,10.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8., 10.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [4]:
vars = tf.Variable([10,7])
vars

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [5]:
vars[0].assign(7)
vars

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [10]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [16]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [17]:
# Make a tensor of all ones
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [18]:

# Make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [19]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [31]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E, tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E), tf.reduce_sum(E).numpy()

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([94, 79, 52, 66, 29, 42, 46, 39, 91, 40, 62, 74,  6, 53,  8,  6, 71,
        59, 69, 42, 39, 71, 97,  1, 83, 82, 89, 93, 14, 81, 16, 33, 12, 92,
        59, 51,  0, 92, 85, 66, 83, 23, 69, 47, 70, 36, 86, 28, 10,  0])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=97>,
 <tf.Tensor: shape=(), dtype=int64, numpy=52>,
 2636)

In [32]:
print(tf.config.list_physical_devices('GPU'))

[]


In [33]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [43]:
A = tf.constant([[10,7,3],
                 [1,2,3]])
B = tf.constant([[5,2],
                 [3,5],
                 [4,6]])
C = tf.matmul(A,B)
D = A @ B
E = tf.reshape(A, shape=(3,2))
A.shape, A.ndim, B.shape, B.ndim, C.shape, C.ndim, C, D.shape, D.ndim, D,E

(TensorShape([2, 3]),
 2,
 TensorShape([3, 2]),
 2,
 TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[83, 73],
        [23, 30]], dtype=int32)>,
 TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[83, 73],
        [23, 30]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  1],
        [ 2,  3]], dtype=int32)>)